- name: Download latest Waterfall on waterfall
  get_url:
    url: https://papermc.io/ci/job/Waterfall/lastStableBuild/artifact/Waterfall-Proxy/bootstrap/target/Waterfall.jar
    dest: /docker/mcnew/waterfall/Waterfall.jar
    mode: '0644'
    owner: 'anthony'
    group: 'dockerfs'
    force: true
  register: result

- name: Download latest SkinsRestorer plugin on waterfall
  get_url:
    url: https://github.com/SkinsRestorer/SkinsRestorerX/releases/latest/download/SkinsRestorer.jar
    dest: /docker/mcnew/waterfall/plugins/SkinsRestorer.jar
    mode: '0644'
    owner: 'anthony'
    group: 'dockerfs'
    force: true
  register: result

- name: Download 5.1.107 BungeeCord LuckPerms on waterfall
  get_url:
    url: https://ci.lucko.me/view/LuckPerms/job/LuckPerms/lastStableBuild/artifact/bungee/build/libs/LuckPerms-Bungee-5.1.107.jar
    dest: /docker/mcnew/waterfall/plugins/LuckPerms-Bungee.jar
    mode: '0644'
    owner: 'anthony'
    group: 'dockerfs'
    force: true
  register: result

- name: Download 1.9.5 Multichat on waterfall
  get_url:
    url: https://github.com/MultiChat/Development/blob/master/multichat/releases/1.9.5/multichat-1.9.5-dev.1.jar?raw=true
    dest: /docker/mcnew/waterfall/plugins/multichat.jar
    mode: '0644'
    owner: 'anthony'
    group:  'dockerfs'
    force: true
  register: result

- name: Download 3.4.1 BungeeTabListPlus on waterfall
  get_url:
    url: https://ci.codecrafter47.de/job/BungeeTabListPlus/lastStableBuild/artifact/bootstrap-bungee/build/libs/BungeeTabListPlus-3.4.1-SNAPSHOT.jar
    dest: /docker/mcnew/waterfall/plugins/BungeeTabListPlus.jar
    mode: '0644'
    owner: 'anthony'
    group:  'dockerfs'
    force: true
  register: result

- name: Download 3.4.1 BungeeTabListPlus (Bukkit Bridge) on mc-server-1
  get_url:
    url: https://ci.codecrafter47.de/job/BungeeTabListPlus/lastStableBuild/artifact/bootstrap-bukkit/build/libs/BungeeTabListPlus_BukkitBridge-3.4.1-SNAPSHOT.jar
    dest: /docker/mcnew/mc-server-1/plugins/BungeeTabListPlus_BukkitBridge.jar
    mode: '0644'
    owner: 'anthony'
    group:  'dockerfs'
    force: true
  register: result

- name: Download 3.1-beta-2 Dynmap on mc-server-1
  get_url:
    url: https://dynmap.us/builds/dynmap/Dynmap-3.1-SNAPSHOT-spigot.jar
    dest: /docker/mcnew/mc-server-1/plugins/Dynmap-spigot.jar
    mode: '0644'
    owner: 'anthony'
    group:  'dockerfs'
    force: true
  register: result    

- name: Download EssentialsX-2.18.1.0 on mc-server-1
  get_url:
    url: https://github.com/EssentialsX/Essentials/releases/download/2.18.1/EssentialsX-2.18.1.0.jar
    dest: /docker/mcnew/mc-server-1/plugins/EssentialsX.jar
    mode: '0644'
    owner: 'anthony'
    group:  'dockerfs'
    force: true
  register: result

- name: Download EssentialsXAntiBuild-2.18.1.0 on mc-server-1
  get_url:
    url: https://github.com/EssentialsX/Essentials/releases/download/2.18.1/EssentialsXAntiBuild-2.18.1.0.jar
    dest: /docker/mcnew/mc-server-1/plugins/EssentialsXAntiBuild.jar
    mode: '0644'
    owner: 'anthony'
    group:  'dockerfs'
    force: true
  register: result

- name: Download EssentialsXGeoIP-2.18.1.0 on mc-server-1
  get_url:
    url: https://github.com/EssentialsX/Essentials/releases/download/2.18.1/EssentialsXGeoIP-2.18.1.0.jar
    dest: /docker/mcnew/mc-server-1/plugins/EssentialsXGeoIP.jar
    mode: '0644'
    owner: 'anthony'
    group:  'dockerfs'
    force: true
  register: result

- name: Download EssentialsXSpawn-2.18.1.0 on mc-server-1
  get_url:
    url: https://github.com/EssentialsX/Essentials/releases/download/2.18.1/EssentialsXSpawn-2.18.1.0.jar
    dest: /docker/mcnew/mc-server-1/plugins/EssentialsXSpawn.jar
    mode: '0644'
    owner: 'anthony'
    group:  'dockerfs'
    force: true
  register: result

- name: Download 5.1.107 LuckPerms on mc-server-1
  get_url:
    url: https://ci.lucko.me/job/LuckPerms/1164/artifact/bukkit/build/libs/LuckPerms-Bukkit-5.1.107.jar
    dest: /docker/mcnew/mc-server-1/plugins/LuckPerms-Bukkit.jar
    mode: '0644'
    owner: 'anthony'
    group:  'dockerfs'
    force: true
  register: result

- name: Download 1.9.5 Multichat on mc-server-1
  get_url:
    url: https://github.com/MultiChat/Development/blob/master/multichat/releases/1.9.5/multichat-1.9.5-dev.1.jar?raw=true
    dest: /docker/mcnew/mc-server-1/plugins/multichat.jar
    mode: '0644'
    owner: 'anthony'
    group:  'dockerfs'
  register: result

- name: Download latest SkinsRestorer plugin on mc-server-1
  get_url:
    url: https://github.com/SkinsRestorer/SkinsRestorerX/releases/latest/download/SkinsRestorer.jar
    dest: /docker/mcnew/mc-server-1/plugins/SkinsRestorer.jar
    mode: '0644'
    owner: 'anthony'
    group:  'dockerfs'
    force: true
  register: result

- name: Download latest vault plugin on mc-server-1
  get_url:
    url: https://github.com/MilkBowl/Vault/releases/latest/download/Vault.jar
    dest: /docker/mcnew/mc-server-1/plugins/Vault.jar
    mode: '0644'
    owner: 'anthony'
    group:  'dockerfs'
    force: true
  register: result

- name: Download latest Geyser plugin on waterfall
  get_url:
    url: https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/lastSuccessfulBuild/artifact/bootstrap/bungeecord/target/Geyser-BungeeCord.jar
    dest: /docker/mcnew/waterfall/plugins/Geyser-BungeeCord.jar
    mode: '0644'
    owner: 'anthony'
    group:  'dockerfs'
    force: true
  register: result

# - name: Download 4.6.3 sleepmost plugin on mc-server-1
#   get_url:
#     url: https://www.spigotmc.org/resources/sleep-most-1-8-1-16-2-configurable-messages-and-percentage.60623/download?version=356526
#     dest: /docker/mcnew/mc-server-1/plugins/sleep-most.jar
#     mode: '0644'
#     owner: 'anthony'
#     group:  'dockerfs'

- name: Announce mincraft server restart
  shell:
    cmd: "{{ broadcast_minecraft_server_reboot }}"
  register: output
  when: result.changed

- name: Restart minecraft server stack
  shell:
    cmd: "{{ restart_minecraft_command }}"
  register: output
  when: result.changed