docker_update_command: docker-compose pull && docker image prune -f && docker container prune -f && docker volume prune -f && docker-compose rm && docker-compose up -d --remove-orphans
docker_compose_pull: docker-compose pull
prune_images_and_containers: docker image prune -f && docker container prune -f
docker_compose_prune: docker-compose rm
docker_compose_up: docker-compose up -d --remove-orphans --compatibility
restart_minecraft_command: docker exec -i mc-server-1 rcon-cli broadcast Network is going for a reboot due to automated updates now! && docker restart minecraft-waterfall && docker restart mc-server-1