- name: Check to see if reboot is required (CentOS)
  command: needs-restarting -r
  register: result
  ignore_errors: yes
  when: ansible_distribution == "CentOS"

#To remove when we see a reboot iniaite with magic.
- name: Display result (CentOS)
  debug:
    var: result.rc
  when: ansible_distribution == "CentOS"
  changed_when: "result.rc != 0"

- name: Reboot servers if necessary
  reboot:
  when: ansible_distribution == "CentOS" and result.rc == 1